import { ArrowLeft, ArrowUpRight, BadgeCheck, Box, Check, Clock3, MapPin, MessageSquareQuote, ShieldCheck, Tag } from "lucide-react";
import { useEffect } from "react";
import { Link, useRoute } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { ProductGallery, parseProductImages } from "@/components/ProductGallery";
import { QuoteCard } from "@/pages/CommercePages";
import { SuraErrorState, SuraPageSkeleton } from "@/components/SuraStates";
import { VibeLayout, formatKes, labelize } from "@/components/VibeLayout";
import { Seo } from "@/components/Seo";
import { useKenyaLocation } from "@/contexts/KenyaLocationContext";
import { trpc } from "@/lib/trpc";
import { useTrackView } from "@/lib/trackView";

type ProductDiscount = { id: number; code: string; title: string; description: string | null; discountType: "percentage" | "fixed_kes"; discountValue: number; minimumSpendKes: number | null; validUntil: Date | string | null; savingsKes: number; salePriceKes: number; label: string };

export default function ProductDetailPage() {
  const [, params] = useRoute("/shop/:id");
  const productId = Number(params?.id ?? 0);
  const { isAuthenticated } = useAuth();
  const { city } = useKenyaLocation();
  const productQuery = trpc.commerce.product.useQuery({ productId }, { enabled: productId > 0 });
  const trackView = useTrackView();
  useEffect(() => { if (productQuery.data) trackView("product", productQuery.data.product.id, productQuery.data.company.id); }, [productQuery.data?.product.id, productQuery.data?.company.id, trackView]);

  if (productQuery.isLoading) return <VibeLayout><main className="px-4 pb-28 pt-8 sm:px-6 lg:px-8"><SuraPageSkeleton cards={2} /></main></VibeLayout>;
  if (productQuery.isError || !productQuery.data) return <VibeLayout><main className="px-4 pb-28 pt-8 sm:px-6 lg:px-8"><SuraErrorState title="This product is not available." copy="The company may have paused the item or it may not yet be visible through the verified shop." onRetry={() => productQuery.refetch()} /><Link href="/shop" className="vb-focus mt-5 inline-flex items-center gap-2 text-sm font-bold text-[var(--sura-accent)]"><ArrowLeft className="h-4 w-4" />Back to connected shops</Link></main></VibeLayout>;

  const { product, company, discounts } = productQuery.data;
  const images = parseProductImages(product);
  const discount = discounts[0] as ProductDiscount | undefined;
  const sizeOptions = parseSizeOptions(product.sizeOptions);
  const cityName = city ?? "Nairobi";

  return <VibeLayout><main className="px-4 pb-32 pt-6 sm:px-6 lg:px-8 lg:pb-16"><Seo title={`${product.name} — ${company.name} on SURA`} description={(product.description ?? `${product.name}, available through verified ${company.name} in ${company.city ?? "Kenya"} with indicative pricing.`).slice(0, 158)} /><nav aria-label="Breadcrumb" className="flex flex-wrap items-center gap-1.5 text-xs font-bold"><Link href="/" className="vb-focus text-[var(--sura-sand)] hover:text-[var(--sura-accent)]">SURA</Link><span className="text-[var(--sura-sand)]/50">/</span><Link href="/shop" className="vb-focus text-[var(--sura-sand)] hover:text-[var(--sura-accent)]">Connected shops</Link><span className="text-[var(--sura-sand)]/50">/</span><Link href={`/company/${company.id}`} className="vb-focus text-[var(--sura-sand)] hover:text-[var(--sura-accent)]">{company.name}</Link><span className="text-[var(--sura-sand)]/50">/</span><span aria-current="page" className="max-w-[16rem] truncate text-[var(--sura-ink)]">{product.name}</span></nav><Link href="/shop" className="vb-focus mt-3 inline-flex items-center gap-2 text-sm font-bold text-[var(--sura-accent)] hover:text-[var(--sura-accent)]"><ArrowLeft className="h-4 w-4" />Back to connected shops</Link><div className="mt-6 grid gap-8 lg:grid-cols-[minmax(0,1.05fr)_minmax(22rem,0.85fr)] lg:items-start">
    <section><ProductGallery images={images} name={product.name} /><div className="mt-4 flex items-center gap-2 text-xs text-[var(--sura-accent-strong)]"><ShieldCheck className="h-3.5 w-3.5 text-[var(--sura-accent)]" />Verified company listing · images and details supplied by the company</div></section>
    <section className="lg:sticky lg:top-24"><div className="flex items-center justify-between gap-3"><p className="vb-kicker text-[var(--sura-terracotta)]">{labelize(product.category)} · {company.city ?? "Kenya"}</p>{product.stockQuantity > 0 && <span className="inline-flex items-center gap-1.5 rounded-full bg-[#eef5d8] px-2.5 py-1.5 text-[0.62rem] font-black uppercase tracking-[0.08em] text-[#53652b] dark:bg-[#263b25] dark:text-[#d8e6b8]"><span className="h-1.5 w-1.5 rounded-full bg-[#8cae35] dark:bg-[#caf240]" />In stock</span>}</div><h1 className="mt-4 text-4xl font-black leading-[0.95] tracking-[-0.06em] text-[var(--sura-ink)] sm:text-5xl">{product.name}</h1><p className="mt-5 text-base leading-7 text-[var(--sura-sand)]">{product.description}</p><div className="mt-6 flex flex-wrap items-end gap-3"><div><p className="text-xs font-semibold text-[var(--sura-accent-strong)]">{discount ? "Member price" : "Company price"}</p><p className="text-4xl font-black tracking-[-0.06em] text-[var(--sura-ink)]">{formatKes(discount?.salePriceKes ?? product.priceKes)}</p></div>{discount && <div className="pb-1"><del className="text-sm text-[var(--sura-accent)]">{formatKes(product.priceKes)}</del><p className="text-xs font-bold text-[#829f31] dark:text-[#b9c796]">You save {formatKes(discount.savingsKes)}</p></div>}</div>
    {discount && <div className="mt-6 rounded-2xl border border-[#c8dc85] bg-[#f0f6dc] p-4 dark:border-[#3d5237] dark:bg-[#1e2616]"><div className="flex items-start gap-3"><Tag className="mt-0.5 h-4 w-4 shrink-0 text-[#708a2e] dark:text-[#caf240]" /><div><p className="text-sm font-black text-[#3f501d] dark:text-[#d8e6b8]">{discount.title} · {discount.label}</p><p className="mt-1 text-xs leading-5 text-[#65763b] dark:text-[#b9c796]">Use code <strong>{discount.code}</strong>{discount.minimumSpendKes ? ` at checkout with a minimum spend of ${formatKes(discount.minimumSpendKes)}.` : "."} {discount.description || "Offer terms are set by the company and reviewed by Sura."}</p></div></div></div>}
    <div className="mt-6 grid grid-cols-2 gap-2 rounded-2xl border border-[var(--sura-border)] bg-[var(--sura-paper)] p-4 text-sm"><div className="flex items-start gap-2"><Box className="mt-0.5 h-4 w-4 text-[var(--sura-accent)]" /><div><p className="text-xs text-[var(--sura-sand)]">Available</p><p className="mt-1 font-bold text-[var(--sura-ink)]">{product.stockQuantity > 0 ? `${product.stockQuantity} units` : "Sold out"}</p></div></div><div className="flex items-start gap-2"><Clock3 className="mt-0.5 h-4 w-4 text-[var(--sura-accent)]" /><div><p className="text-xs text-[var(--sura-sand)]">Delivery</p><p className="mt-1 font-bold text-[var(--sura-ink)]">From {cityName}</p></div></div></div>
    {sizeOptions.length > 0 && <div className="mt-5"><p className="text-xs font-black uppercase tracking-[0.08em] text-[var(--sura-sand)]">Available options</p><div className="mt-2 flex flex-wrap gap-2">{sizeOptions.map((size) => <span key={size} className="rounded-full border border-[var(--sura-border)] bg-[var(--sura-paper)] px-3 py-2 text-xs font-bold text-[var(--sura-sand)]">{size}</span>)}</div></div>}
    <div className="mt-6 rounded-2xl border border-[var(--sura-border)] bg-[var(--sura-paper)] p-5"><div className="flex items-start gap-3"><BadgeCheck className="mt-0.5 h-5 w-5 shrink-0 text-[var(--sura-accent)]" /><div><p className="text-sm font-black text-[var(--sura-ink)]">{company.name}</p><p className="mt-1 flex items-center gap-1 text-xs text-[var(--sura-ink)]/75"><MapPin className="h-3 w-3" />{company.city ?? "Kenya"} · Verified Sura company</p><Link href={`/company/${company.id}`} className="vb-focus mt-3 inline-flex items-center gap-1 text-xs font-bold text-[var(--sura-accent)]">View company space <ArrowUpRight className="h-3.5 w-3.5" /></Link></div></div></div>
    <QuoteCard productId={product.id} city={cityName} isAuthenticated={isAuthenticated} /></section>
  </div><section className="mt-10   pt-8"><div className="grid gap-5 md:grid-cols-3"><InfoBlock title="Clear description" copy="Companies provide the product details, options, and fulfilment context shown on this page." /><InfoBlock title="Transparent price" copy="Discounts are shown beside the original company price and only activate after Sura approval." /><InfoBlock title="Verified route" copy="Only active products from verified companies appear in connected shops." /></div></section><div className="fixed inset-x-0 bottom-[calc(4.55rem+env(safe-area-inset-bottom))] z-50 px-4 lg:hidden"><div className="mx-auto flex max-w-md items-center gap-3 rounded-2xl border border-[var(--sura-border)] bg-[color-mix(in_srgb,var(--sura-paper)_92%,transparent)] p-3 shadow-[0_-10px_34px_rgba(31,26,16,0.14)] backdrop-blur-xl"><div className="min-w-0 shrink-0"><p className="text-[0.6rem] font-semibold text-[var(--sura-accent)]">{discount ? "Member price" : "Company price"}</p><p className="text-lg font-black leading-tight text-[var(--sura-ink)]">{formatKes(discount?.salePriceKes ?? product.priceKes)}</p></div><button onClick={() => document.getElementById("sura-quote-card")?.scrollIntoView({ behavior: "smooth", block: "start" })} className="vb-button vb-focus inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-[var(--sura-signal)] px-5 py-3 text-sm font-extrabold text-[var(--sura-on-signal)]"><MessageSquareQuote className="h-4 w-4" />Request a quote</button></div></div></main></VibeLayout>;
}

function InfoBlock({ title, copy }: { title: string; copy: string }) { return <div className="rounded-2xl border border-[var(--sura-border)] bg-[var(--sura-paper)] p-5"><Check className="h-4 w-4 text-[var(--sura-accent)]" /><h2 className="mt-4 text-sm font-black text-[var(--sura-ink)]">{title}</h2><p className="mt-2 text-xs leading-5 text-[var(--sura-sand)]">{copy}</p></div>; }
function parseSizeOptions(value: string | null) { try { const parsed = JSON.parse(value || "[]"); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === "string" && item.length > 0) : []; } catch { return []; } }
