import { ArrowUpRight, CircleAlert, Link2, Loader2, MapPin } from "lucide-react";
import { Link, useRoute } from "wouter";
import { VibeLayout, formatKes } from "@/components/VibeLayout";
import { VendorCard } from "@/components/VendorCard";
import { Seo } from "@/components/Seo";
import { trpc } from "@/lib/trpc";
import type { DemoBuild, DemoVendor } from "../../../server/vibebuild-data";

type SharedBuildData = { title: string; summary: string | null; createdAt: Date; builds: DemoBuild[]; vendors: DemoVendor[] };

export default function SharedBuild() {
  const [, params] = useRoute("/share/:token");
  const share = trpc.shares.byToken.useQuery({ token: params?.token ?? "" }, { enabled: Boolean(params?.token) });
  if (share.isLoading) return <VibeLayout><main className="container grid min-h-[60vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[var(--sura-accent)]" /><p className="vb-serif mt-4 text-2xl text-[var(--sura-ink)]">Opening this shared edit…</p></div></main></VibeLayout>;
  if (share.isError || !share.data) return <VibeLayout><main className="container grid min-h-[60vh] place-items-center"><div className="max-w-md rounded-[1.5rem] border border-[#ddb09f] bg-[var(--sura-paper)] p-8 text-center"><CircleAlert className="mx-auto h-6 w-6 text-[#a04932]" /><h1 className="vb-serif mt-3 text-3xl text-[#5e2b20]">This link is not available.</h1><p className="mt-2 text-sm leading-6 text-[#7c4637]">It may have been removed, or it might not have been ready to share yet.</p><Link href="/" className="vb-button vb-focus mt-5 inline-flex rounded-xl bg-[#592b20] px-5 py-2.5 text-sm font-bold text-white">Explore SURA</Link></div></main></VibeLayout>;
  const data = share.data as SharedBuildData;
  return <VibeLayout><main className="container pb-20 pt-12 sm:pt-16"><Seo title={`${data.title} — A shared SURA edit`} description={(data.summary || "A collection of local sources and directions, shared from a SURA planning board.").slice(0, 158)} /><div className="max-w-3xl"><span className="vb-kicker text-[var(--sura-terracotta)]">A shared SURA edit</span><h1 className="vb-serif mt-4 text-5xl leading-[0.94] tracking-[-0.045em] text-[var(--sura-ink)] sm:text-6xl">{data.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-[var(--sura-sand)]">{data.summary || "A collection of local sources and directions, shared from a SURA planning board."}</p><p className="mt-4 inline-flex items-center gap-2 rounded-full bg-[var(--sura-soft)] px-3 py-1.5 text-xs font-bold text-[var(--sura-ochre)]"><Link2 className="h-3.5 w-3.5" />Public share</p></div>{data.builds.length > 0 && <section className="mt-12"><div className="flex items-center justify-between"><h2 className="vb-serif text-3xl text-[var(--sura-ink)]">Build directions</h2><span className="text-sm text-[var(--sura-sand)]">{data.builds.length} saved</span></div><div className="mt-5 grid gap-5 lg:grid-cols-2">{data.builds.map((build) => <article key={build.id} className="overflow-hidden rounded-[1.6rem] border border-[var(--sura-border)] bg-[var(--sura-paper)]"><img src={build.heroImageUrl} alt="Shared build direction" className="h-52 w-full object-cover" /><div className="p-6"><span className="vb-kicker text-[var(--sura-terracotta)]">From {formatKes(build.totalMinKes)}</span><h3 className="vb-serif mt-3 text-3xl text-[var(--sura-ink)]">{build.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--sura-sand)]">{build.headline}</p></div></article>)}</div></section>}{data.vendors.length > 0 && <section className="mt-12"><div className="flex items-center justify-between"><h2 className="vb-serif text-3xl text-[var(--sura-ink)]">Local sources</h2><span className="inline-flex items-center gap-1 text-sm text-[var(--sura-sand)]"><MapPin className="h-3.5 w-3.5 text-[var(--sura-sand)]" />Kenya</span></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{data.vendors.map((vendor) => <VendorCard key={vendor.id} vendor={vendor} />)}</div></section>}<section className="mt-14 rounded-2xl bg-[var(--sura-primary)] p-7 text-[#faf4ea] sm:flex sm:items-center sm:justify-between"><div><p className="vb-kicker text-[#e0a863]">Shape your own direction</p><p className="vb-serif mt-2 text-3xl">Start with the number that works for you.</p></div><Link href="/brief" className="vb-button vb-focus mt-5 inline-flex items-center gap-2 rounded-xl bg-[var(--sura-paper)] px-5 py-3 text-sm font-bold text-[var(--sura-ink)] sm:mt-0">Build your edit <ArrowUpRight className="h-4 w-4" /></Link></section></main></VibeLayout>;
}
