import { ArrowLeft, ArrowUpRight, Bookmark, CheckCircle2, CircleAlert, Instagram, Loader2, MapPin, MessageCircle, Timer } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { InquiryPanel } from "@/components/InquiryPanel";
import { VibeLayout, formatKes, labelize } from "@/components/VibeLayout";
import { SuraImage } from "@/components/SuraImage";
import { Seo } from "@/components/Seo";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";

export default function VendorProfile() {
  const [, params] = useRoute("/vendors/:slug");
  const [, setLocation] = useLocation();
  const slug = params?.slug ?? "";
  const { isAuthenticated } = useAuth();
  const vendor = trpc.vendors.bySlug.useQuery({ slug }, { enabled: Boolean(slug) });
  const savedVendorIds = trpc.board.savedVendorIds.useQuery(undefined, { enabled: isAuthenticated });
  const saveVendor = trpc.board.saveVendor.useMutation({ onSuccess: () => savedVendorIds.refetch() });

  if (vendor.isLoading) return <VibeLayout><main className="container grid min-h-[60vh] place-items-center"><div className="text-center"><Loader2 className="mx-auto h-7 w-7 animate-spin text-[var(--sura-accent)]" /><p className="vb-serif mt-4 text-2xl text-[var(--sura-ink)]">Opening the profile…</p></div></main></VibeLayout>;
  if (vendor.isError || !vendor.data) return <VibeLayout><main className="container grid min-h-[60vh] place-items-center"><div className="max-w-md rounded-[1.5rem] border border-[#ddb09f] bg-[var(--sura-paper)] p-8 text-center"><CircleAlert className="mx-auto h-6 w-6 text-[#a04932]" /><h1 className="vb-serif mt-3 text-3xl text-[#5e2b20]">That profile is not available.</h1><p className="mt-2 text-sm leading-6 text-[#7c4637]">Return to the directory to keep exploring local directions.</p><Link href="/discover" className="vb-button vb-focus mt-5 inline-flex rounded-xl bg-[#592b20] px-5 py-2.5 text-sm font-bold text-white">Back to directory</Link></div></main></VibeLayout>;

  const profile = vendor.data;
  const isSaved = ((savedVendorIds.data ?? []) as number[]).includes(profile.id);
  const save = () => isAuthenticated ? saveVendor.mutate({ vendorId: profile.id, shouldSave: !isSaved }) : startLogin();

  return <VibeLayout><main>
    <Seo title={`${profile.name} — Local maker in ${profile.city}`} description={profile.description?.slice(0, 158) ?? `${profile.name} is a ${labelize(profile.type)} serving ${profile.neighbourhood}, ${profile.city}. Pricing is indicative; confirm before committing.`} />
    <div className="container pt-8"><button onClick={() => setLocation("/discover")} className="vb-focus inline-flex items-center gap-2 text-sm font-semibold text-[var(--sura-accent)] hover:text-[var(--sura-accent)]"><ArrowLeft className="h-4 w-4" />Back to the directory</button></div>
    <section className="container grid gap-8 pb-16 pt-7 lg:grid-cols-[1.03fr_0.97fr] lg:gap-12 lg:pb-24"><div className="relative min-h-[27rem] overflow-hidden rounded-2xl bg-[#bd8d65] sm:min-h-[34rem]"><SuraImage src={profile.portfolio[0]} fallbackSrc="/assets/sura-auth-street.jpg" alt={`${profile.name} demonstration portfolio`} className="h-full w-full object-cover" /><div className="absolute inset-x-5 bottom-5 flex items-end justify-between gap-4 rounded-2xl border border-white/25 bg-[var(--sura-primary)]/80 p-4 text-[#fff9f0] backdrop-blur-md"><div><p className="vb-kicker text-[#e1aa62]">Local maker</p><p className="mt-1 text-sm text-[var(--sura-ink)]/55">Details shown are indicative; confirm before committing.</p></div><span className="rounded-full border border-white/25 px-3 py-1.5 text-xs font-bold">{labelize(profile.type)}</span></div></div><div className="flex flex-col justify-center"><div className="flex flex-wrap items-center gap-3"><span className="vb-kicker text-[var(--sura-terracotta)]">{profile.city} · {profile.neighbourhood}</span><span className="rounded-full bg-[var(--sura-soft)] px-3 py-1.5 text-[0.65rem] font-bold uppercase tracking-[0.09em] text-[var(--sura-sand)]">Indicative pricing</span></div><h1 className="vb-serif mt-5 text-5xl leading-[0.94] tracking-[-0.045em] text-[var(--sura-ink)] sm:text-6xl">{profile.name}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-[var(--sura-sand)]">{profile.description}</p><div className="mt-7  border-[var(--sura-border)] py-5"><p className="vb-kicker text-[var(--sura-terracotta)]">Point of view</p><p className="vb-serif mt-3 text-2xl leading-[1.14] text-[var(--sura-ink)]">“{profile.pointOfView}”</p></div><div className="mt-7 flex flex-wrap gap-2">{profile.aestheticTags.map((tag) => <span key={tag} className="rounded-full border border-[var(--sura-border)] bg-[var(--sura-paper)] px-3 py-2 text-xs font-semibold text-[var(--sura-sand)]">{tag}</span>)}</div><div className="mt-8 flex flex-wrap gap-3"><InquiryPanel vendorId={profile.id} contextName={profile.name} /><button onClick={save} disabled={saveVendor.isPending} className="vb-button vb-focus inline-flex items-center gap-2 rounded-full border border-[var(--sura-border)] bg-[var(--sura-paper)] px-5 py-3.5 text-sm font-semibold text-[var(--sura-ink)] hover:border-[var(--sura-accent)] disabled:opacity-70">{isSaved ? <CheckCircle2 className="h-4 w-4 text-[var(--sura-accent)]" /> : <Bookmark className="h-4 w-4" />}{isSaved ? "Saved to board" : "Save this studio"}</button><a href={profile.socialUrl} target="_blank" rel="noreferrer" className="vb-focus inline-flex items-center gap-2 rounded-full border border-[var(--sura-border)] bg-[var(--sura-paper)] px-5 py-3.5 text-sm font-semibold text-[var(--sura-ink)] hover:border-[var(--sura-accent)]"><Instagram className="h-4 w-4" />{profile.socialHandle}</a></div></div></section>
    <section className=" vb-rule bg-[var(--sura-soft)]"><div className="container grid gap-10 py-14 lg:grid-cols-[0.9fr_1.1fr]"><div><span className="vb-kicker text-[var(--sura-terracotta)]">Services & spend</span><h2 className="vb-serif mt-4 text-4xl leading-[0.98] tracking-[-0.04em] text-[var(--sura-ink)]">A clear starting range.</h2><p className="mt-4 max-w-sm text-sm leading-6 text-[var(--sura-sand)]">Prices are indicative. Ask for a current quote before you commit.</p><div className="mt-6 flex items-center gap-2 text-sm font-semibold text-[var(--sura-ink)]"><MapPin className="h-4 w-4 text-[var(--sura-ochre)]" />{profile.locationText}</div></div><div className="   ">{profile.services.map((service) => <div key={service.title} className="grid gap-3 py-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-bold text-[var(--sura-ink)]">{service.title}</p><p className="mt-1 text-sm text-[var(--sura-sand)]">{service.category} · {service.leadTime}</p></div><strong className="text-sm text-[var(--sura-ink)]">{formatKes(service.priceFromKes)}–{formatKes(service.priceToKes)}</strong></div>)}</div></div></section>
    <section className="container grid gap-6 py-16 sm:grid-cols-[1fr_0.9fr] sm:items-center sm:py-20"><div><span className="vb-kicker text-[var(--sura-terracotta)]">The next step is personal</span><h2 className="vb-serif mt-4 max-w-xl text-4xl leading-[0.98] tracking-[-0.04em] text-[var(--sura-ink)] sm:text-5xl">Bring the build context with you.</h2><p className="mt-4 max-w-lg text-base leading-7 text-[var(--sura-sand)]">Start with a short build brief to give the conversation a point of view, budget, and useful direction. The structured inquiry is stored with this studio and the context you share.</p></div><div className="rounded-2xl bg-[var(--sura-primary)] p-6 text-[#f9f2e9] sm:p-8"><MessageCircle className="h-6 w-6 text-[#d69b58]" /><p className="vb-serif mt-7 text-3xl leading-[1.02]">“A good inquiry gives the maker something real to respond to.”</p><div className="mt-7 flex items-center justify-between   pt-4 text-xs text-[var(--sura-ink)]/60"><span className="inline-flex items-center gap-2"><Timer className="h-3.5 w-3.5 text-[#d69b58]" />Stored with context</span><button onClick={() => setLocation("/brief")} className="vb-button vb-focus inline-flex items-center gap-2 font-bold text-[#f6c88b]">Build a plan <ArrowUpRight className="h-3.5 w-3.5" /></button></div></div></section>
  </main></VibeLayout>;
}
